version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www           
      
      - ./nginx/conf.d:/etc/nginx/conf.d  
    ports:
      - "8083:80"  
    depends_on:
      - php  

  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www 
    expose:
      - "9000"  
